{-# OPTIONS_GHC -fno-warn-overlapping-patterns #-}
-- | Parser for obelisk.  Generated by happy.  See happy/obelisk.y
module Language.Obelisk.Parser where

import Prelude hiding (lex)

import Language.Obelisk.Parser.Monad hiding (eparse, run_parser)
import qualified Language.Obelisk.Parser.Monad as M

import Language.Obelisk.Lexer
import Language.Obelisk.Lexer.Token

import Language.Obelisk.AST.Simple

parse :: Parse

terror :: Token -> OParser a
terror = fail . ("Caused by token: " ++) . show 

-- Convienence parsers
run_parser :: FilePath -> String -> SimpleObelisk
run_parser = M.run_parser parse

eparse :: FilePath -> String -> ParseResult SimpleObelisk
eparse = M.eparse parse

-- parser produced by Happy Version 1.18.4

data HappyAbsSyn 
	= HappyTerminal (Token)
	| HappyErrorToken Int
	| HappyAbsSyn4 (CodeFragment)
	| HappyAbsSyn5 (QType)
	| HappyAbsSyn6 (Type)
	| HappyAbsSyn7 ([TypeName])
	| HappyAbsSyn8 (TypeName)
	| HappyAbsSyn9 (SimpleObelisk)
	| HappyAbsSyn10 ([SimpleFDef])
	| HappyAbsSyn11 ([SimpleDef])
	| HappyAbsSyn12 (SimpleFDef)
	| HappyAbsSyn13 (SimpleDef)
	| HappyAbsSyn15 ([String])
	| HappyAbsSyn16 (SimpleExp)
	| HappyAbsSyn21 ([SimpleExp])
	| HappyAbsSyn26 (SimpleBlock)

{- to allow type-synonyms as our monads (likely
 - with explicitly-specified bind and return)
 - in Haskell98, it seems that with
 - /type M a = .../, then /(HappyReduction M)/
 - is not allowed.  But Happy is a
 - code-generator that can just substitute it.
type HappyReduction m = 
	   Int 
	-> (Token)
	-> HappyState (Token) (HappyStk HappyAbsSyn -> m HappyAbsSyn)
	-> [HappyState (Token) (HappyStk HappyAbsSyn -> m HappyAbsSyn)] 
	-> HappyStk HappyAbsSyn 
	-> m HappyAbsSyn
-}

action_0,
 action_1,
 action_2,
 action_3,
 action_4,
 action_5,
 action_6,
 action_7,
 action_8,
 action_9,
 action_10,
 action_11,
 action_12,
 action_13,
 action_14,
 action_15,
 action_16,
 action_17,
 action_18,
 action_19,
 action_20,
 action_21,
 action_22,
 action_23,
 action_24,
 action_25,
 action_26,
 action_27,
 action_28,
 action_29,
 action_30,
 action_31,
 action_32,
 action_33,
 action_34,
 action_35,
 action_36,
 action_37,
 action_38,
 action_39,
 action_40,
 action_41,
 action_42,
 action_43,
 action_44,
 action_45,
 action_46,
 action_47,
 action_48,
 action_49,
 action_50,
 action_51,
 action_52,
 action_53,
 action_54,
 action_55,
 action_56,
 action_57,
 action_58,
 action_59,
 action_60,
 action_61,
 action_62,
 action_63 :: () => Int -> ({-HappyReduction (OParser) = -}
	   Int 
	-> (Token)
	-> HappyState (Token) (HappyStk HappyAbsSyn -> (OParser) HappyAbsSyn)
	-> [HappyState (Token) (HappyStk HappyAbsSyn -> (OParser) HappyAbsSyn)] 
	-> HappyStk HappyAbsSyn 
	-> (OParser) HappyAbsSyn)

happyReduce_1,
 happyReduce_2,
 happyReduce_3,
 happyReduce_4,
 happyReduce_5,
 happyReduce_6,
 happyReduce_7,
 happyReduce_8,
 happyReduce_9,
 happyReduce_10,
 happyReduce_11,
 happyReduce_12,
 happyReduce_13,
 happyReduce_14,
 happyReduce_15,
 happyReduce_16,
 happyReduce_17,
 happyReduce_18,
 happyReduce_19,
 happyReduce_20,
 happyReduce_21,
 happyReduce_22,
 happyReduce_23,
 happyReduce_24,
 happyReduce_25,
 happyReduce_26,
 happyReduce_27,
 happyReduce_28,
 happyReduce_29,
 happyReduce_30,
 happyReduce_31,
 happyReduce_32,
 happyReduce_33,
 happyReduce_34,
 happyReduce_35,
 happyReduce_36 :: () => ({-HappyReduction (OParser) = -}
	   Int 
	-> (Token)
	-> HappyState (Token) (HappyStk HappyAbsSyn -> (OParser) HappyAbsSyn)
	-> [HappyState (Token) (HappyStk HappyAbsSyn -> (OParser) HappyAbsSyn)] 
	-> HappyStk HappyAbsSyn 
	-> (OParser) HappyAbsSyn)

action_0 (9) = happyGoto action_2
action_0 (10) = happyGoto action_3
action_0 _ = happyReduce_9

action_1 _ = happyFail

action_2 (41) = happyAccept
action_2 _ = happyFail

action_3 (39) = happyShift action_4
action_3 _ = happyReduce_7

action_4 (4) = happyGoto action_5
action_4 (12) = happyGoto action_6
action_4 _ = happyReduce_1

action_5 (36) = happyShift action_12
action_5 (5) = happyGoto action_8
action_5 (6) = happyGoto action_9
action_5 (7) = happyGoto action_10
action_5 (8) = happyGoto action_11
action_5 _ = happyFail

action_6 (40) = happyShift action_7
action_6 _ = happyFail

action_7 _ = happyReduce_8

action_8 (27) = happyShift action_15
action_8 _ = happyFail

action_9 (38) = happyShift action_14
action_9 _ = happyFail

action_10 (37) = happyShift action_13
action_10 _ = happyReduce_3

action_11 _ = happyReduce_5

action_12 _ = happyReduce_6

action_13 (36) = happyShift action_12
action_13 (8) = happyGoto action_17
action_13 _ = happyFail

action_14 _ = happyReduce_2

action_15 (30) = happyShift action_16
action_15 _ = happyFail

action_16 (15) = happyGoto action_18
action_16 _ = happyReduce_17

action_17 _ = happyReduce_4

action_18 (30) = happyShift action_21
action_18 (4) = happyGoto action_19
action_18 (26) = happyGoto action_20
action_18 _ = happyReduce_1

action_19 (39) = happyShift action_24
action_19 _ = happyFail

action_20 (34) = happyShift action_23
action_20 (14) = happyGoto action_22
action_20 _ = happyReduce_16

action_21 _ = happyReduce_18

action_22 _ = happyReduce_12

action_23 (39) = happyShift action_26
action_23 _ = happyFail

action_24 (21) = happyGoto action_25
action_24 _ = happyReduce_29

action_25 (39) = happyShift action_34
action_25 (40) = happyShift action_35
action_25 (4) = happyGoto action_28
action_25 (17) = happyGoto action_29
action_25 (18) = happyGoto action_30
action_25 (23) = happyGoto action_31
action_25 (24) = happyGoto action_32
action_25 (25) = happyGoto action_33
action_25 _ = happyReduce_1

action_26 (11) = happyGoto action_27
action_26 _ = happyReduce_11

action_27 (39) = happyShift action_45
action_27 (40) = happyShift action_46
action_27 _ = happyFail

action_28 (29) = happyShift action_41
action_28 (30) = happyShift action_42
action_28 (32) = happyShift action_43
action_28 (33) = happyShift action_44
action_28 _ = happyFail

action_29 _ = happyReduce_23

action_30 _ = happyReduce_30

action_31 _ = happyReduce_20

action_32 _ = happyReduce_21

action_33 _ = happyReduce_22

action_34 (4) = happyGoto action_36
action_34 (16) = happyGoto action_37
action_34 (19) = happyGoto action_38
action_34 (20) = happyGoto action_39
action_34 (22) = happyGoto action_40
action_34 _ = happyReduce_1

action_35 _ = happyReduce_36

action_36 (28) = happyShift action_52
action_36 (39) = happyShift action_34
action_36 (4) = happyGoto action_28
action_36 (17) = happyGoto action_29
action_36 (18) = happyGoto action_51
action_36 (23) = happyGoto action_31
action_36 (24) = happyGoto action_32
action_36 (25) = happyGoto action_33
action_36 _ = happyReduce_1

action_37 _ = happyReduce_27

action_38 (40) = happyShift action_50
action_38 _ = happyFail

action_39 _ = happyReduce_25

action_40 _ = happyReduce_26

action_41 _ = happyReduce_33

action_42 _ = happyReduce_32

action_43 _ = happyReduce_34

action_44 _ = happyReduce_35

action_45 (4) = happyGoto action_47
action_45 (12) = happyGoto action_48
action_45 (13) = happyGoto action_49
action_45 _ = happyReduce_1

action_46 _ = happyReduce_15

action_47 (36) = happyShift action_12
action_47 (5) = happyGoto action_57
action_47 (6) = happyGoto action_9
action_47 (7) = happyGoto action_10
action_47 (8) = happyGoto action_11
action_47 _ = happyFail

action_48 _ = happyReduce_13

action_49 (40) = happyShift action_56
action_49 _ = happyFail

action_50 _ = happyReduce_24

action_51 (31) = happyShift action_55
action_51 (21) = happyGoto action_54
action_51 _ = happyReduce_29

action_52 (39) = happyShift action_34
action_52 (4) = happyGoto action_28
action_52 (17) = happyGoto action_29
action_52 (18) = happyGoto action_53
action_52 (23) = happyGoto action_31
action_52 (24) = happyGoto action_32
action_52 (25) = happyGoto action_33
action_52 _ = happyReduce_1

action_53 (4) = happyGoto action_19
action_53 (26) = happyGoto action_60
action_53 _ = happyReduce_1

action_54 (39) = happyShift action_34
action_54 (40) = happyReduce_28
action_54 (4) = happyGoto action_28
action_54 (17) = happyGoto action_29
action_54 (18) = happyGoto action_30
action_54 (23) = happyGoto action_31
action_54 (24) = happyGoto action_32
action_54 (25) = happyGoto action_33
action_54 _ = happyReduce_1

action_55 (39) = happyShift action_34
action_55 (4) = happyGoto action_28
action_55 (17) = happyGoto action_29
action_55 (18) = happyGoto action_59
action_55 (23) = happyGoto action_31
action_55 (24) = happyGoto action_32
action_55 (25) = happyGoto action_33
action_55 _ = happyReduce_1

action_56 _ = happyReduce_10

action_57 (27) = happyShift action_15
action_57 (35) = happyShift action_58
action_57 _ = happyFail

action_58 (30) = happyShift action_62
action_58 _ = happyFail

action_59 _ = happyReduce_31

action_60 (4) = happyGoto action_19
action_60 (26) = happyGoto action_61
action_60 _ = happyReduce_1

action_61 _ = happyReduce_19

action_62 (39) = happyShift action_34
action_62 (4) = happyGoto action_28
action_62 (17) = happyGoto action_29
action_62 (18) = happyGoto action_63
action_62 (23) = happyGoto action_31
action_62 (24) = happyGoto action_32
action_62 (25) = happyGoto action_33
action_62 _ = happyReduce_1

action_63 _ = happyReduce_14

happyReduce_1 = happyMonadReduce 0 4 happyReduction_1
happyReduction_1 (happyRest) tk
	 = happyThen (( get_pos)
	) (\r -> happyReturn (HappyAbsSyn4 r))

happyReduce_2 = happySpecReduce_2  5 happyReduction_2
happyReduction_2 _
	(HappyAbsSyn6  happy_var_1)
	 =  HappyAbsSyn5
		 (QType [] happy_var_1
	)
happyReduction_2 _ _  = notHappyAtAll 

happyReduce_3 = happySpecReduce_1  6 happyReduction_3
happyReduction_3 (HappyAbsSyn7  happy_var_1)
	 =  HappyAbsSyn6
		 (Type $ reverse happy_var_1
	)
happyReduction_3 _  = notHappyAtAll 

happyReduce_4 = happySpecReduce_3  7 happyReduction_4
happyReduction_4 (HappyAbsSyn8  happy_var_3)
	_
	(HappyAbsSyn7  happy_var_1)
	 =  HappyAbsSyn7
		 (happy_var_3 : happy_var_1
	)
happyReduction_4 _ _ _  = notHappyAtAll 

happyReduce_5 = happySpecReduce_1  7 happyReduction_5
happyReduction_5 (HappyAbsSyn8  happy_var_1)
	 =  HappyAbsSyn7
		 ([happy_var_1]
	)
happyReduction_5 _  = notHappyAtAll 

happyReduce_6 = happySpecReduce_1  8 happyReduction_6
happyReduction_6 (HappyTerminal (TClassName happy_var_1))
	 =  HappyAbsSyn8
		 (TypeClassName happy_var_1
	)
happyReduction_6 _  = notHappyAtAll 

happyReduce_7 = happySpecReduce_1  9 happyReduction_7
happyReduction_7 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn9
		 (Obelisk $ reverse happy_var_1
	)
happyReduction_7 _  = notHappyAtAll 

happyReduce_8 = happyReduce 4 10 happyReduction_8
happyReduction_8 (_ `HappyStk`
	(HappyAbsSyn12  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn10  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn10
		 (happy_var_3 : happy_var_1
	) `HappyStk` happyRest

happyReduce_9 = happySpecReduce_0  10 happyReduction_9
happyReduction_9  =  HappyAbsSyn10
		 ([]
	)

happyReduce_10 = happyReduce 4 11 happyReduction_10
happyReduction_10 (_ `HappyStk`
	(HappyAbsSyn13  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn11  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn11
		 (happy_var_3 : happy_var_1
	) `HappyStk` happyRest

happyReduce_11 = happySpecReduce_0  11 happyReduction_11
happyReduction_11  =  HappyAbsSyn11
		 ([]
	)

happyReduce_12 = happyReduce 7 12 happyReduction_12
happyReduction_12 ((HappyAbsSyn11  happy_var_7) `HappyStk`
	(HappyAbsSyn26  happy_var_6) `HappyStk`
	(HappyAbsSyn15  happy_var_5) `HappyStk`
	(HappyTerminal (TVar happy_var_4)) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn5  happy_var_2) `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (Def happy_var_1 happy_var_2 happy_var_4 happy_var_5 happy_var_6 happy_var_7
	) `HappyStk` happyRest

happyReduce_13 = happySpecReduce_1  13 happyReduction_13
happyReduction_13 (HappyAbsSyn12  happy_var_1)
	 =  HappyAbsSyn13
		 (FDef happy_var_1
	)
happyReduction_13 _  = notHappyAtAll 

happyReduce_14 = happyReduce 5 13 happyReduction_14
happyReduction_14 ((HappyAbsSyn16  happy_var_5) `HappyStk`
	(HappyTerminal (TVar happy_var_4)) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn5  happy_var_2) `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (Constant happy_var_1 happy_var_2 happy_var_4 happy_var_5
	) `HappyStk` happyRest

happyReduce_15 = happyReduce 4 14 happyReduction_15
happyReduction_15 (_ `HappyStk`
	(HappyAbsSyn11  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn11
		 (happy_var_3
	) `HappyStk` happyRest

happyReduce_16 = happySpecReduce_0  14 happyReduction_16
happyReduction_16  =  HappyAbsSyn11
		 ([]
	)

happyReduce_17 = happySpecReduce_0  15 happyReduction_17
happyReduction_17  =  HappyAbsSyn15
		 ([]
	)

happyReduce_18 = happySpecReduce_2  15 happyReduction_18
happyReduction_18 (HappyTerminal (TVar happy_var_2))
	(HappyAbsSyn15  happy_var_1)
	 =  HappyAbsSyn15
		 (happy_var_2 : happy_var_1
	)
happyReduction_18 _ _  = notHappyAtAll 

happyReduce_19 = happyReduce 5 16 happyReduction_19
happyReduction_19 ((HappyAbsSyn26  happy_var_5) `HappyStk`
	(HappyAbsSyn26  happy_var_4) `HappyStk`
	(HappyAbsSyn16  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn16
		 (If happy_var_1 happy_var_3 happy_var_4 happy_var_5
	) `HappyStk` happyRest

happyReduce_20 = happySpecReduce_1  17 happyReduction_20
happyReduction_20 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn16
		 (happy_var_1
	)
happyReduction_20 _  = notHappyAtAll 

happyReduce_21 = happySpecReduce_1  17 happyReduction_21
happyReduction_21 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn16
		 (happy_var_1
	)
happyReduction_21 _  = notHappyAtAll 

happyReduce_22 = happySpecReduce_1  17 happyReduction_22
happyReduction_22 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn16
		 (happy_var_1
	)
happyReduction_22 _  = notHappyAtAll 

happyReduce_23 = happySpecReduce_1  18 happyReduction_23
happyReduction_23 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn16
		 (happy_var_1
	)
happyReduction_23 _  = notHappyAtAll 

happyReduce_24 = happySpecReduce_3  18 happyReduction_24
happyReduction_24 _
	(HappyAbsSyn16  happy_var_2)
	_
	 =  HappyAbsSyn16
		 (happy_var_2
	)
happyReduction_24 _ _ _  = notHappyAtAll 

happyReduce_25 = happySpecReduce_1  19 happyReduction_25
happyReduction_25 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn16
		 (happy_var_1
	)
happyReduction_25 _  = notHappyAtAll 

happyReduce_26 = happySpecReduce_1  19 happyReduction_26
happyReduction_26 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn16
		 (happy_var_1
	)
happyReduction_26 _  = notHappyAtAll 

happyReduce_27 = happySpecReduce_1  19 happyReduction_27
happyReduction_27 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn16
		 (happy_var_1
	)
happyReduction_27 _  = notHappyAtAll 

happyReduce_28 = happySpecReduce_3  20 happyReduction_28
happyReduction_28 (HappyAbsSyn21  happy_var_3)
	(HappyAbsSyn16  happy_var_2)
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn16
		 (Apply happy_var_1 happy_var_2 happy_var_3
	)
happyReduction_28 _ _ _  = notHappyAtAll 

happyReduce_29 = happySpecReduce_0  21 happyReduction_29
happyReduction_29  =  HappyAbsSyn21
		 ([]
	)

happyReduce_30 = happySpecReduce_2  21 happyReduction_30
happyReduction_30 (HappyAbsSyn16  happy_var_2)
	(HappyAbsSyn21  happy_var_1)
	 =  HappyAbsSyn21
		 (happy_var_2 : happy_var_1
	)
happyReduction_30 _ _  = notHappyAtAll 

happyReduce_31 = happyReduce 4 22 happyReduction_31
happyReduction_31 ((HappyAbsSyn16  happy_var_4) `HappyStk`
	(HappyTerminal (TOp happy_var_3)) `HappyStk`
	(HappyAbsSyn16  happy_var_2) `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn16
		 (Infix happy_var_1 happy_var_2 happy_var_3 happy_var_4
	) `HappyStk` happyRest

happyReduce_32 = happySpecReduce_2  23 happyReduction_32
happyReduction_32 (HappyTerminal (TVar happy_var_2))
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn16
		 (OVar happy_var_1 happy_var_2
	)
happyReduction_32 _ _  = notHappyAtAll 

happyReduce_33 = happySpecReduce_2  24 happyReduction_33
happyReduction_33 (HappyTerminal (TInt happy_var_2))
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn16
		 (OInt happy_var_1 happy_var_2
	)
happyReduction_33 _ _  = notHappyAtAll 

happyReduce_34 = happySpecReduce_2  25 happyReduction_34
happyReduction_34 _
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn16
		 (OBool happy_var_1 True
	)
happyReduction_34 _ _  = notHappyAtAll 

happyReduce_35 = happySpecReduce_2  25 happyReduction_35
happyReduction_35 _
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn16
		 (OBool happy_var_1 False
	)
happyReduction_35 _ _  = notHappyAtAll 

happyReduce_36 = happyReduce 4 26 happyReduction_36
happyReduction_36 (_ `HappyStk`
	(HappyAbsSyn21  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn26
		 (Block happy_var_1 (reverse happy_var_3)
	) `HappyStk` happyRest

happyNewToken action sts stk
	= lex(\tk -> 
	let cont i = action i i tk (HappyState action) sts stk in
	case tk of {
	TEOF -> action 41 41 tk (HappyState action) sts stk;
	TDef -> cont 27;
	TIf -> cont 28;
	TInt happy_dollar_dollar -> cont 29;
	TVar happy_dollar_dollar -> cont 30;
	TOp happy_dollar_dollar -> cont 31;
	TTrue -> cont 32;
	TFalse -> cont 33;
	TWhere -> cont 34;
	TConstant -> cont 35;
	TClassName happy_dollar_dollar -> cont 36;
	TArrow -> cont 37;
	TTypeTerm -> cont 38;
	TParOpen -> cont 39;
	TParClose -> cont 40;
	_ -> happyError' tk
	})

happyError_ tk = happyError' tk

happyThen :: () => OParser a -> (a -> OParser b) -> OParser b
happyThen = (>>=)
happyReturn :: () => a -> OParser a
happyReturn = (return)
happyThen1 = happyThen
happyReturn1 :: () => a -> OParser a
happyReturn1 = happyReturn
happyError' :: () => (Token) -> OParser a
happyError' tk = terror tk

parse = happySomeParser where
  happySomeParser = happyThen (happyParse action_0) (\x -> case x of {HappyAbsSyn9 z -> happyReturn z; _other -> notHappyAtAll })

happySeq = happyDontSeq



{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "<built-in>" #-}
{-# LINE 1 "<command-line>" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
-- Id: GenericTemplate.hs,v 1.26 2005/01/14 14:47:22 simonmar Exp 

{-# LINE 28 "templates/GenericTemplate.hs" #-}








{-# LINE 49 "templates/GenericTemplate.hs" #-}

{-# LINE 59 "templates/GenericTemplate.hs" #-}

{-# LINE 68 "templates/GenericTemplate.hs" #-}

infixr 9 `HappyStk`
data HappyStk a = HappyStk a (HappyStk a)

-----------------------------------------------------------------------------
-- starting the parse

happyParse start_state = happyNewToken start_state notHappyAtAll notHappyAtAll

-----------------------------------------------------------------------------
-- Accepting the parse

-- If the current token is (1), it means we've just accepted a partial
-- parse (a %partial parser).  We must ignore the saved token on the top of
-- the stack in this case.
happyAccept (1) tk st sts (_ `HappyStk` ans `HappyStk` _) =
	happyReturn1 ans
happyAccept j tk st sts (HappyStk ans _) = 
	 (happyReturn1 ans)

-----------------------------------------------------------------------------
-- Arrays only: do the next action

{-# LINE 155 "templates/GenericTemplate.hs" #-}

-----------------------------------------------------------------------------
-- HappyState data type (not arrays)



newtype HappyState b c = HappyState
        (Int ->                    -- token number
         Int ->                    -- token number (yes, again)
         b ->                           -- token semantic value
         HappyState b c ->              -- current state
         [HappyState b c] ->            -- state stack
         c)



-----------------------------------------------------------------------------
-- Shifting a token

happyShift new_state (1) tk st sts stk@(x `HappyStk` _) =
     let i = (case x of { HappyErrorToken (i) -> i }) in
--     trace "shifting the error token" $
     new_state i i tk (HappyState (new_state)) ((st):(sts)) (stk)

happyShift new_state i tk st sts stk =
     happyNewToken new_state ((st):(sts)) ((HappyTerminal (tk))`HappyStk`stk)

-- happyReduce is specialised for the common cases.

happySpecReduce_0 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_0 nt fn j tk st@((HappyState (action))) sts stk
     = action nt j tk st ((st):(sts)) (fn `HappyStk` stk)

happySpecReduce_1 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_1 nt fn j tk _ sts@(((st@(HappyState (action))):(_))) (v1`HappyStk`stk')
     = let r = fn v1 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_2 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_2 nt fn j tk _ ((_):(sts@(((st@(HappyState (action))):(_))))) (v1`HappyStk`v2`HappyStk`stk')
     = let r = fn v1 v2 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_3 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_3 nt fn j tk _ ((_):(((_):(sts@(((st@(HappyState (action))):(_))))))) (v1`HappyStk`v2`HappyStk`v3`HappyStk`stk')
     = let r = fn v1 v2 v3 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happyReduce k i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyReduce k nt fn j tk st sts stk
     = case happyDrop (k - ((1) :: Int)) sts of
	 sts1@(((st1@(HappyState (action))):(_))) ->
        	let r = fn stk in  -- it doesn't hurt to always seq here...
       		happyDoSeq r (action nt j tk st1 sts1 r)

happyMonadReduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonadReduce k nt fn j tk st sts stk =
        happyThen1 (fn stk tk) (\r -> action nt j tk st1 sts1 (r `HappyStk` drop_stk))
       where sts1@(((st1@(HappyState (action))):(_))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk

happyMonad2Reduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
       happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
       where sts1@(((st1@(HappyState (action))):(_))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk





             new_state = action


happyDrop (0) l = l
happyDrop n ((_):(t)) = happyDrop (n - ((1) :: Int)) t

happyDropStk (0) l = l
happyDropStk n (x `HappyStk` xs) = happyDropStk (n - ((1)::Int)) xs

-----------------------------------------------------------------------------
-- Moving to a new state after a reduction

{-# LINE 253 "templates/GenericTemplate.hs" #-}
happyGoto action j tk st = action j j tk (HappyState action)


-----------------------------------------------------------------------------
-- Error recovery ((1) is the error token)

-- parse error if we are in recovery and we fail again
happyFail  (1) tk old_st _ stk =
--	trace "failing" $ 
    	happyError_ tk

{-  We don't need state discarding for our restricted implementation of
    "error".  In fact, it can cause some bogus parses, so I've disabled it
    for now --SDM

-- discard a state
happyFail  (1) tk old_st (((HappyState (action))):(sts)) 
						(saved_tok `HappyStk` _ `HappyStk` stk) =
--	trace ("discarding state, depth " ++ show (length stk))  $
	action (1) (1) tk (HappyState (action)) sts ((saved_tok`HappyStk`stk))
-}

-- Enter error recovery: generate an error token,
--                       save the old token and carry on.
happyFail  i tk (HappyState (action)) sts stk =
--      trace "entering error recovery" $
	action (1) (1) tk (HappyState (action)) sts ( (HappyErrorToken (i)) `HappyStk` stk)

-- Internal happy errors:

notHappyAtAll = error "Internal Happy error\n"

-----------------------------------------------------------------------------
-- Hack to get the typechecker to accept our action functions







-----------------------------------------------------------------------------
-- Seq-ing.  If the --strict flag is given, then Happy emits 
--	happySeq = happyDoSeq
-- otherwise it emits
-- 	happySeq = happyDontSeq

happyDoSeq, happyDontSeq :: a -> b -> b
happyDoSeq   a b = a `seq` b
happyDontSeq a b = b

-----------------------------------------------------------------------------
-- Don't inline any functions from the template.  GHC has a nasty habit
-- of deciding to inline happyGoto everywhere, which increases the size of
-- the generated parser quite a bit.

{-# LINE 317 "templates/GenericTemplate.hs" #-}
{-# NOINLINE happyShift #-}
{-# NOINLINE happySpecReduce_0 #-}
{-# NOINLINE happySpecReduce_1 #-}
{-# NOINLINE happySpecReduce_2 #-}
{-# NOINLINE happySpecReduce_3 #-}
{-# NOINLINE happyReduce #-}
{-# NOINLINE happyMonadReduce #-}
{-# NOINLINE happyGoto #-}
{-# NOINLINE happyFail #-}

-- end of Happy Template.
