{-# OPTIONS_GHC -fno-warn-overlapping-patterns #-}
-- | Parser for obelisk.  Generated by happy.  See happy/obelisk.y
module Language.Obelisk.Parser where

import Prelude hiding (lex)

import Language.Obelisk.Parser.Monad as M

import Language.Obelisk.Lexer
import Language.Obelisk.Lexer.Token

import Language.Obelisk.AST.Simple

parse :: Parse

terror :: Token -> OParser a
terror = fail . ("Caused by token: " ++) . show 

-- Convienence parsers
run_parser :: FilePath -> String -> IO SimpleObelisk
run_parser = M.run_parser parse

eparse :: FilePath -> String -> ParseResult SimpleObelisk
eparse = M.eparse parse

-- parser produced by Happy Version 1.18.4

data HappyAbsSyn 
	= HappyTerminal (Token)
	| HappyErrorToken Int
	| HappyAbsSyn4 (CodeFragment)
	| HappyAbsSyn5 (SimpleObelisk)
	| HappyAbsSyn6 ([SimpleDef])
	| HappyAbsSyn7 (SimpleDef)
	| HappyAbsSyn9 ([String])
	| HappyAbsSyn10 (SimpleExp)
	| HappyAbsSyn15 ([SimpleExp])
	| HappyAbsSyn20 (SimpleBlock)

{- to allow type-synonyms as our monads (likely
 - with explicitly-specified bind and return)
 - in Haskell98, it seems that with
 - /type M a = .../, then /(HappyReduction M)/
 - is not allowed.  But Happy is a
 - code-generator that can just substitute it.
type HappyReduction m = 
	   Int 
	-> (Token)
	-> HappyState (Token) (HappyStk HappyAbsSyn -> m HappyAbsSyn)
	-> [HappyState (Token) (HappyStk HappyAbsSyn -> m HappyAbsSyn)] 
	-> HappyStk HappyAbsSyn 
	-> m HappyAbsSyn
-}

action_0,
 action_1,
 action_2,
 action_3,
 action_4,
 action_5,
 action_6,
 action_7,
 action_8,
 action_9,
 action_10,
 action_11,
 action_12,
 action_13,
 action_14,
 action_15,
 action_16,
 action_17,
 action_18,
 action_19,
 action_20,
 action_21,
 action_22,
 action_23,
 action_24,
 action_25,
 action_26,
 action_27,
 action_28,
 action_29,
 action_30,
 action_31,
 action_32,
 action_33,
 action_34,
 action_35,
 action_36,
 action_37,
 action_38,
 action_39,
 action_40,
 action_41,
 action_42,
 action_43,
 action_44,
 action_45,
 action_46,
 action_47,
 action_48,
 action_49 :: () => Int -> ({-HappyReduction (OParser) = -}
	   Int 
	-> (Token)
	-> HappyState (Token) (HappyStk HappyAbsSyn -> (OParser) HappyAbsSyn)
	-> [HappyState (Token) (HappyStk HappyAbsSyn -> (OParser) HappyAbsSyn)] 
	-> HappyStk HappyAbsSyn 
	-> (OParser) HappyAbsSyn)

happyReduce_1,
 happyReduce_2,
 happyReduce_3,
 happyReduce_4,
 happyReduce_5,
 happyReduce_6,
 happyReduce_7,
 happyReduce_8,
 happyReduce_9,
 happyReduce_10,
 happyReduce_11,
 happyReduce_12,
 happyReduce_13,
 happyReduce_14,
 happyReduce_15,
 happyReduce_16,
 happyReduce_17,
 happyReduce_18,
 happyReduce_19,
 happyReduce_20,
 happyReduce_21,
 happyReduce_22,
 happyReduce_23,
 happyReduce_24,
 happyReduce_25,
 happyReduce_26,
 happyReduce_27,
 happyReduce_28 :: () => ({-HappyReduction (OParser) = -}
	   Int 
	-> (Token)
	-> HappyState (Token) (HappyStk HappyAbsSyn -> (OParser) HappyAbsSyn)
	-> [HappyState (Token) (HappyStk HappyAbsSyn -> (OParser) HappyAbsSyn)] 
	-> HappyStk HappyAbsSyn 
	-> (OParser) HappyAbsSyn)

action_0 (5) = happyGoto action_2
action_0 (6) = happyGoto action_3
action_0 _ = happyReduce_4

action_1 _ = happyFail

action_2 (32) = happyAccept
action_2 _ = happyFail

action_3 (30) = happyShift action_4
action_3 _ = happyReduce_2

action_4 (4) = happyGoto action_5
action_4 (7) = happyGoto action_6
action_4 _ = happyReduce_1

action_5 (21) = happyShift action_8
action_5 (29) = happyShift action_9
action_5 _ = happyFail

action_6 (31) = happyShift action_7
action_6 _ = happyFail

action_7 _ = happyReduce_3

action_8 (24) = happyShift action_11
action_8 _ = happyFail

action_9 (24) = happyShift action_10
action_9 _ = happyFail

action_10 (30) = happyShift action_19
action_10 (4) = happyGoto action_13
action_10 (11) = happyGoto action_14
action_10 (12) = happyGoto action_15
action_10 (17) = happyGoto action_16
action_10 (18) = happyGoto action_17
action_10 (19) = happyGoto action_18
action_10 _ = happyReduce_1

action_11 (9) = happyGoto action_12
action_11 _ = happyReduce_9

action_12 (24) = happyShift action_31
action_12 (4) = happyGoto action_29
action_12 (20) = happyGoto action_30
action_12 _ = happyReduce_1

action_13 (23) = happyShift action_25
action_13 (24) = happyShift action_26
action_13 (26) = happyShift action_27
action_13 (27) = happyShift action_28
action_13 _ = happyFail

action_14 _ = happyReduce_15

action_15 _ = happyReduce_6

action_16 _ = happyReduce_12

action_17 _ = happyReduce_13

action_18 _ = happyReduce_14

action_19 (4) = happyGoto action_20
action_19 (10) = happyGoto action_21
action_19 (13) = happyGoto action_22
action_19 (14) = happyGoto action_23
action_19 (16) = happyGoto action_24
action_19 _ = happyReduce_1

action_20 (22) = happyShift action_37
action_20 (30) = happyShift action_19
action_20 (4) = happyGoto action_13
action_20 (11) = happyGoto action_14
action_20 (12) = happyGoto action_36
action_20 (17) = happyGoto action_16
action_20 (18) = happyGoto action_17
action_20 (19) = happyGoto action_18
action_20 _ = happyReduce_1

action_21 _ = happyReduce_19

action_22 (31) = happyShift action_35
action_22 _ = happyFail

action_23 _ = happyReduce_17

action_24 _ = happyReduce_18

action_25 _ = happyReduce_25

action_26 _ = happyReduce_24

action_27 _ = happyReduce_26

action_28 _ = happyReduce_27

action_29 (30) = happyShift action_34
action_29 _ = happyFail

action_30 (28) = happyShift action_33
action_30 (8) = happyGoto action_32
action_30 _ = happyReduce_8

action_31 _ = happyReduce_10

action_32 _ = happyReduce_5

action_33 (30) = happyShift action_42
action_33 _ = happyFail

action_34 (15) = happyGoto action_41
action_34 _ = happyReduce_21

action_35 _ = happyReduce_16

action_36 (25) = happyShift action_40
action_36 (15) = happyGoto action_39
action_36 _ = happyReduce_21

action_37 (30) = happyShift action_19
action_37 (4) = happyGoto action_13
action_37 (11) = happyGoto action_14
action_37 (12) = happyGoto action_38
action_37 (17) = happyGoto action_16
action_37 (18) = happyGoto action_17
action_37 (19) = happyGoto action_18
action_37 _ = happyReduce_1

action_38 (4) = happyGoto action_29
action_38 (20) = happyGoto action_47
action_38 _ = happyReduce_1

action_39 (30) = happyShift action_19
action_39 (31) = happyReduce_20
action_39 (4) = happyGoto action_13
action_39 (11) = happyGoto action_14
action_39 (12) = happyGoto action_44
action_39 (17) = happyGoto action_16
action_39 (18) = happyGoto action_17
action_39 (19) = happyGoto action_18
action_39 _ = happyReduce_1

action_40 (30) = happyShift action_19
action_40 (4) = happyGoto action_13
action_40 (11) = happyGoto action_14
action_40 (12) = happyGoto action_46
action_40 (17) = happyGoto action_16
action_40 (18) = happyGoto action_17
action_40 (19) = happyGoto action_18
action_40 _ = happyReduce_1

action_41 (30) = happyShift action_19
action_41 (31) = happyShift action_45
action_41 (4) = happyGoto action_13
action_41 (11) = happyGoto action_14
action_41 (12) = happyGoto action_44
action_41 (17) = happyGoto action_16
action_41 (18) = happyGoto action_17
action_41 (19) = happyGoto action_18
action_41 _ = happyReduce_1

action_42 (6) = happyGoto action_43
action_42 _ = happyReduce_4

action_43 (30) = happyShift action_4
action_43 (31) = happyShift action_49
action_43 _ = happyFail

action_44 _ = happyReduce_22

action_45 _ = happyReduce_28

action_46 _ = happyReduce_23

action_47 (4) = happyGoto action_29
action_47 (20) = happyGoto action_48
action_47 _ = happyReduce_1

action_48 _ = happyReduce_11

action_49 _ = happyReduce_7

happyReduce_1 = happyMonadReduce 0 4 happyReduction_1
happyReduction_1 (happyRest) tk
	 = happyThen (( get_pos)
	) (\r -> happyReturn (HappyAbsSyn4 r))

happyReduce_2 = happySpecReduce_1  5 happyReduction_2
happyReduction_2 (HappyAbsSyn6  happy_var_1)
	 =  HappyAbsSyn5
		 (Obelisk $ reverse happy_var_1
	)
happyReduction_2 _  = notHappyAtAll 

happyReduce_3 = happyReduce 4 6 happyReduction_3
happyReduction_3 (_ `HappyStk`
	(HappyAbsSyn7  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn6  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn6
		 (happy_var_3 : happy_var_1
	) `HappyStk` happyRest

happyReduce_4 = happySpecReduce_0  6 happyReduction_4
happyReduction_4  =  HappyAbsSyn6
		 ([]
	)

happyReduce_5 = happyReduce 6 7 happyReduction_5
happyReduction_5 ((HappyAbsSyn6  happy_var_6) `HappyStk`
	(HappyAbsSyn20  happy_var_5) `HappyStk`
	(HappyAbsSyn9  happy_var_4) `HappyStk`
	(HappyTerminal (TVar happy_var_3)) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (Def happy_var_1 happy_var_3 happy_var_4 happy_var_5 happy_var_6
	) `HappyStk` happyRest

happyReduce_6 = happyReduce 4 7 happyReduction_6
happyReduction_6 ((HappyAbsSyn10  happy_var_4) `HappyStk`
	(HappyTerminal (TVar happy_var_3)) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (Constant happy_var_1 happy_var_3 happy_var_4
	) `HappyStk` happyRest

happyReduce_7 = happyReduce 4 8 happyReduction_7
happyReduction_7 (_ `HappyStk`
	(HappyAbsSyn6  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn6
		 (happy_var_3
	) `HappyStk` happyRest

happyReduce_8 = happySpecReduce_0  8 happyReduction_8
happyReduction_8  =  HappyAbsSyn6
		 ([]
	)

happyReduce_9 = happySpecReduce_0  9 happyReduction_9
happyReduction_9  =  HappyAbsSyn9
		 ([]
	)

happyReduce_10 = happySpecReduce_2  9 happyReduction_10
happyReduction_10 (HappyTerminal (TVar happy_var_2))
	(HappyAbsSyn9  happy_var_1)
	 =  HappyAbsSyn9
		 (happy_var_2 : happy_var_1
	)
happyReduction_10 _ _  = notHappyAtAll 

happyReduce_11 = happyReduce 5 10 happyReduction_11
happyReduction_11 ((HappyAbsSyn20  happy_var_5) `HappyStk`
	(HappyAbsSyn20  happy_var_4) `HappyStk`
	(HappyAbsSyn10  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn10
		 (If happy_var_1 happy_var_3 happy_var_4 happy_var_5
	) `HappyStk` happyRest

happyReduce_12 = happySpecReduce_1  11 happyReduction_12
happyReduction_12 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn10
		 (happy_var_1
	)
happyReduction_12 _  = notHappyAtAll 

happyReduce_13 = happySpecReduce_1  11 happyReduction_13
happyReduction_13 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn10
		 (happy_var_1
	)
happyReduction_13 _  = notHappyAtAll 

happyReduce_14 = happySpecReduce_1  11 happyReduction_14
happyReduction_14 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn10
		 (happy_var_1
	)
happyReduction_14 _  = notHappyAtAll 

happyReduce_15 = happySpecReduce_1  12 happyReduction_15
happyReduction_15 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn10
		 (happy_var_1
	)
happyReduction_15 _  = notHappyAtAll 

happyReduce_16 = happySpecReduce_3  12 happyReduction_16
happyReduction_16 _
	(HappyAbsSyn10  happy_var_2)
	_
	 =  HappyAbsSyn10
		 (happy_var_2
	)
happyReduction_16 _ _ _  = notHappyAtAll 

happyReduce_17 = happySpecReduce_1  13 happyReduction_17
happyReduction_17 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn10
		 (happy_var_1
	)
happyReduction_17 _  = notHappyAtAll 

happyReduce_18 = happySpecReduce_1  13 happyReduction_18
happyReduction_18 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn10
		 (happy_var_1
	)
happyReduction_18 _  = notHappyAtAll 

happyReduce_19 = happySpecReduce_1  13 happyReduction_19
happyReduction_19 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn10
		 (happy_var_1
	)
happyReduction_19 _  = notHappyAtAll 

happyReduce_20 = happySpecReduce_3  14 happyReduction_20
happyReduction_20 (HappyAbsSyn15  happy_var_3)
	(HappyAbsSyn10  happy_var_2)
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn10
		 (Apply happy_var_1 happy_var_2 happy_var_3
	)
happyReduction_20 _ _ _  = notHappyAtAll 

happyReduce_21 = happySpecReduce_0  15 happyReduction_21
happyReduction_21  =  HappyAbsSyn15
		 ([]
	)

happyReduce_22 = happySpecReduce_2  15 happyReduction_22
happyReduction_22 (HappyAbsSyn10  happy_var_2)
	(HappyAbsSyn15  happy_var_1)
	 =  HappyAbsSyn15
		 (happy_var_2 : happy_var_1
	)
happyReduction_22 _ _  = notHappyAtAll 

happyReduce_23 = happyReduce 4 16 happyReduction_23
happyReduction_23 ((HappyAbsSyn10  happy_var_4) `HappyStk`
	(HappyTerminal (TOp happy_var_3)) `HappyStk`
	(HappyAbsSyn10  happy_var_2) `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn10
		 (Infix happy_var_1 happy_var_2 happy_var_3 happy_var_4
	) `HappyStk` happyRest

happyReduce_24 = happySpecReduce_2  17 happyReduction_24
happyReduction_24 (HappyTerminal (TVar happy_var_2))
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn10
		 (OVar happy_var_1 happy_var_2
	)
happyReduction_24 _ _  = notHappyAtAll 

happyReduce_25 = happySpecReduce_2  18 happyReduction_25
happyReduction_25 (HappyTerminal (TInt happy_var_2))
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn10
		 (OInt happy_var_1 happy_var_2
	)
happyReduction_25 _ _  = notHappyAtAll 

happyReduce_26 = happySpecReduce_2  19 happyReduction_26
happyReduction_26 _
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn10
		 (OBool happy_var_1 True
	)
happyReduction_26 _ _  = notHappyAtAll 

happyReduce_27 = happySpecReduce_2  19 happyReduction_27
happyReduction_27 _
	(HappyAbsSyn4  happy_var_1)
	 =  HappyAbsSyn10
		 (OBool happy_var_1 False
	)
happyReduction_27 _ _  = notHappyAtAll 

happyReduce_28 = happyReduce 4 20 happyReduction_28
happyReduction_28 (_ `HappyStk`
	(HappyAbsSyn15  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn4  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn20
		 (Block happy_var_1 (reverse happy_var_3)
	) `HappyStk` happyRest

happyNewToken action sts stk
	= lex(\tk -> 
	let cont i = action i i tk (HappyState action) sts stk in
	case tk of {
	TEOF -> action 32 32 tk (HappyState action) sts stk;
	TDef -> cont 21;
	TIf -> cont 22;
	TInt happy_dollar_dollar -> cont 23;
	TVar happy_dollar_dollar -> cont 24;
	TOp happy_dollar_dollar -> cont 25;
	TTrue -> cont 26;
	TFalse -> cont 27;
	TWhere -> cont 28;
	TConstant -> cont 29;
	TParOpen -> cont 30;
	TParClose -> cont 31;
	_ -> happyError' tk
	})

happyError_ tk = happyError' tk

happyThen :: () => OParser a -> (a -> OParser b) -> OParser b
happyThen = (>>=)
happyReturn :: () => a -> OParser a
happyReturn = (return)
happyThen1 = happyThen
happyReturn1 :: () => a -> OParser a
happyReturn1 = happyReturn
happyError' :: () => (Token) -> OParser a
happyError' tk = terror tk

parse = happySomeParser where
  happySomeParser = happyThen (happyParse action_0) (\x -> case x of {HappyAbsSyn5 z -> happyReturn z; _other -> notHappyAtAll })

happySeq = happyDontSeq



{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "<built-in>" #-}
{-# LINE 1 "<command-line>" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
-- Id: GenericTemplate.hs,v 1.26 2005/01/14 14:47:22 simonmar Exp 

{-# LINE 28 "templates/GenericTemplate.hs" #-}








{-# LINE 49 "templates/GenericTemplate.hs" #-}

{-# LINE 59 "templates/GenericTemplate.hs" #-}

{-# LINE 68 "templates/GenericTemplate.hs" #-}

infixr 9 `HappyStk`
data HappyStk a = HappyStk a (HappyStk a)

-----------------------------------------------------------------------------
-- starting the parse

happyParse start_state = happyNewToken start_state notHappyAtAll notHappyAtAll

-----------------------------------------------------------------------------
-- Accepting the parse

-- If the current token is (1), it means we've just accepted a partial
-- parse (a %partial parser).  We must ignore the saved token on the top of
-- the stack in this case.
happyAccept (1) tk st sts (_ `HappyStk` ans `HappyStk` _) =
	happyReturn1 ans
happyAccept j tk st sts (HappyStk ans _) = 
	 (happyReturn1 ans)

-----------------------------------------------------------------------------
-- Arrays only: do the next action

{-# LINE 155 "templates/GenericTemplate.hs" #-}

-----------------------------------------------------------------------------
-- HappyState data type (not arrays)



newtype HappyState b c = HappyState
        (Int ->                    -- token number
         Int ->                    -- token number (yes, again)
         b ->                           -- token semantic value
         HappyState b c ->              -- current state
         [HappyState b c] ->            -- state stack
         c)



-----------------------------------------------------------------------------
-- Shifting a token

happyShift new_state (1) tk st sts stk@(x `HappyStk` _) =
     let i = (case x of { HappyErrorToken (i) -> i }) in
--     trace "shifting the error token" $
     new_state i i tk (HappyState (new_state)) ((st):(sts)) (stk)

happyShift new_state i tk st sts stk =
     happyNewToken new_state ((st):(sts)) ((HappyTerminal (tk))`HappyStk`stk)

-- happyReduce is specialised for the common cases.

happySpecReduce_0 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_0 nt fn j tk st@((HappyState (action))) sts stk
     = action nt j tk st ((st):(sts)) (fn `HappyStk` stk)

happySpecReduce_1 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_1 nt fn j tk _ sts@(((st@(HappyState (action))):(_))) (v1`HappyStk`stk')
     = let r = fn v1 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_2 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_2 nt fn j tk _ ((_):(sts@(((st@(HappyState (action))):(_))))) (v1`HappyStk`v2`HappyStk`stk')
     = let r = fn v1 v2 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_3 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_3 nt fn j tk _ ((_):(((_):(sts@(((st@(HappyState (action))):(_))))))) (v1`HappyStk`v2`HappyStk`v3`HappyStk`stk')
     = let r = fn v1 v2 v3 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happyReduce k i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyReduce k nt fn j tk st sts stk
     = case happyDrop (k - ((1) :: Int)) sts of
	 sts1@(((st1@(HappyState (action))):(_))) ->
        	let r = fn stk in  -- it doesn't hurt to always seq here...
       		happyDoSeq r (action nt j tk st1 sts1 r)

happyMonadReduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonadReduce k nt fn j tk st sts stk =
        happyThen1 (fn stk tk) (\r -> action nt j tk st1 sts1 (r `HappyStk` drop_stk))
       where sts1@(((st1@(HappyState (action))):(_))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk

happyMonad2Reduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
       happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
       where sts1@(((st1@(HappyState (action))):(_))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk





             new_state = action


happyDrop (0) l = l
happyDrop n ((_):(t)) = happyDrop (n - ((1) :: Int)) t

happyDropStk (0) l = l
happyDropStk n (x `HappyStk` xs) = happyDropStk (n - ((1)::Int)) xs

-----------------------------------------------------------------------------
-- Moving to a new state after a reduction

{-# LINE 253 "templates/GenericTemplate.hs" #-}
happyGoto action j tk st = action j j tk (HappyState action)


-----------------------------------------------------------------------------
-- Error recovery ((1) is the error token)

-- parse error if we are in recovery and we fail again
happyFail  (1) tk old_st _ stk =
--	trace "failing" $ 
    	happyError_ tk

{-  We don't need state discarding for our restricted implementation of
    "error".  In fact, it can cause some bogus parses, so I've disabled it
    for now --SDM

-- discard a state
happyFail  (1) tk old_st (((HappyState (action))):(sts)) 
						(saved_tok `HappyStk` _ `HappyStk` stk) =
--	trace ("discarding state, depth " ++ show (length stk))  $
	action (1) (1) tk (HappyState (action)) sts ((saved_tok`HappyStk`stk))
-}

-- Enter error recovery: generate an error token,
--                       save the old token and carry on.
happyFail  i tk (HappyState (action)) sts stk =
--      trace "entering error recovery" $
	action (1) (1) tk (HappyState (action)) sts ( (HappyErrorToken (i)) `HappyStk` stk)

-- Internal happy errors:

notHappyAtAll = error "Internal Happy error\n"

-----------------------------------------------------------------------------
-- Hack to get the typechecker to accept our action functions







-----------------------------------------------------------------------------
-- Seq-ing.  If the --strict flag is given, then Happy emits 
--	happySeq = happyDoSeq
-- otherwise it emits
-- 	happySeq = happyDontSeq

happyDoSeq, happyDontSeq :: a -> b -> b
happyDoSeq   a b = a `seq` b
happyDontSeq a b = b

-----------------------------------------------------------------------------
-- Don't inline any functions from the template.  GHC has a nasty habit
-- of deciding to inline happyGoto everywhere, which increases the size of
-- the generated parser quite a bit.

{-# LINE 317 "templates/GenericTemplate.hs" #-}
{-# NOINLINE happyShift #-}
{-# NOINLINE happySpecReduce_0 #-}
{-# NOINLINE happySpecReduce_1 #-}
{-# NOINLINE happySpecReduce_2 #-}
{-# NOINLINE happySpecReduce_3 #-}
{-# NOINLINE happyReduce #-}
{-# NOINLINE happyMonadReduce #-}
{-# NOINLINE happyGoto #-}
{-# NOINLINE happyFail #-}

-- end of Happy Template.
